do-checkpoint: True
job-modes:
  - validate
  - test
dataset:
  name: wn18rr
  num_entities: 40943
  num_relations: 11
train:
  model_type: ensemble
ensemble:
  base_ranker_checkpoint_path: out/wn18rr/t1/checkpoints/checkpoint_best.ckpt
  reranker_checkpoint_path: out/wn18rr/crossencoder.ckpt
  answer_selector_checkpoint_path: out/wn18rr/t1_prune/checkpoints/checkpoint_best.ckpt
  answer_selector_type: dynamic
  quantile: 0.9
search:
  parameters:
  - bounds:
    - 0.05
    - 0.95
    name: ensemble.reranker_weight_head_batch
    type: range
    value_type: float
  - bounds:
    - 0.05
    - 0.95
    name: ensemble.reranker_weight_tail_batch
    type: range
    value_type: float