do-checkpoint: True
job-modes:
  - validate
  - test
dataset:
  name: fb15k-237
  num_entities: 14541
  num_relations: 237
train:
  model_type: ensemble
ensemble:
  base_ranker_checkpoint_path: out/fb15k-237/t1/checkpoints/checkpoint_best.ckpt
  reranker_checkpoint_path: out/fb15k-237/crossencoder.ckpt
  answer_selector_checkpoint_path: out/fb15k-237/t1_prune/checkpoints/checkpoint_best.ckpt
  answer_selector_type: dynamic
  quantile: 0.9
search:
  parameters:
  - bounds:
    - 0.05
    - 0.95
    name: ensemble.reranker_weight_head_batch
    type: range
    value_type: float
  - bounds:
    - 0.05
    - 0.95
    name: ensemble.reranker_weight_tail_batch
    type: range
    value_type: float