do-checkpoint: True
monitor:
  metric: mrr_quantile_0.9
dataset:
  name: fb15k-237
  num_entities: 14541
  num_relations: 237
  splits:
    train: valid_train
    valid: valid_dev
    test:
      - valid
      - test
train:
  model_type: answer_selector
  batch_size: 16
  max_epochs: 100
  lr: 0.001
eval:
  check_val_every_n: 5
answer_selector:
  base_ranker_checkpoint_path: out/fb15k-237/t1/checkpoints/checkpoint_best.ckpt